# Generated by Django 4.2.5 on 2023-09-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_note', '0002_alter_blog_note_content_alter_blog_note_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_note',
            name='quantity_views',
            field=models.IntegerField(default=0, verbose_name='Счетчик просмотров'),
        ),
        migrations.AlterField(
            model_name='blog_note',
            name='sign_of_publication',
            field=models.BooleanField(default=True, verbose_name='Признак публикации'),
        ),
    ]
