# Generated by Django 4.2.5 on 2023-09-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_date_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.CharField(default=1, max_length=100, verbose_name='created_at'),
            preserve_default=False,
        ),
    ]
