# Generated by Django 4.2.5 on 2023-10-01 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_image_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='name',
            new_name='version_name',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='number',
            new_name='version_number',
        ),
        migrations.RemoveField(
            model_name='version',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='version',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='product_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.version', verbose_name='Версия'),
        ),
        migrations.AddField(
            model_name='version',
            name='version_attribute',
            field=models.BooleanField(default=False, verbose_name='Актуальная версия'),
        ),
    ]
