# Generated by Django 4.2.5 on 2023-10-01 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_rename_name_version_version_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_version',
        ),
        migrations.AddField(
            model_name='version',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_attribute',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Актуальная версия'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название версии'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер версии'),
        ),
    ]
