# Generated by Django 4.2.5 on 2023-10-01 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_product_product_version_version_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.version', verbose_name='Версия'),
        ),
    ]
