# Generated by Django 4.2.5 on 2023-10-01 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_product_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_version',
        ),
    ]
