# Generated by Django 4.2.5 on 2023-10-01 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_product_product_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='version_attribute',
            new_name='attribute',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='version_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='version_number',
            new_name='number',
        ),
    ]
